
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Ictshop.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Post
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Post()
    {

        this.PostTagMaps = new HashSet<PostTagMap>();

    }


    public int Id { get; set; }

    public string Title { get; set; }

    public string ShortDescription { get; set; }

    public string PostContent { get; set; }

    public string Anh { get; set; }

    public bool Published { get; set; }

    public System.DateTime Posted_on { get; set; }

    public string Url { get; set; }

    public System.DateTime Modified { get; set; }

    public string Mota { get; set; }

    public Nullable<int> CategoryId { get; set; }



    public virtual Category Category { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PostTagMap> PostTagMaps { get; set; }

}

}
