
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Ictshop.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Sanpham
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Sanpham()
    {

        this.Chitietdonhangs = new HashSet<Chitietdonhang>();

    }


    public int Masp { get; set; }

    public string Tensp { get; set; }

    public decimal Giatien { get; set; }

    public int Soluong { get; set; }

    public string Mota { get; set; }

    public int Thesim { get; set; }

    public int Bonhotrong { get; set; }

    public bool Sanphammoi { get; set; }

    public int Ram { get; set; }

    public string Anhbia { get; set; }

    public int Mahang { get; set; }

    public int Mahdh { get; set; }

    public string Kichco { get; set; }

    public string Chatluong { get; set; }

    public string Xuatxu { get; set; }



    public virtual Hangsanxuat Hangsanxuat { get; set; }

    public virtual Hedieuhanh Hedieuhanh { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Chitietdonhang> Chitietdonhangs { get; set; }

}

}
